In [5]:
import numpy as np
import pandas as pd
import re
import datetime 

from pathlib import Path

DATA_PATH = Path("__file__").absolute().parent / 'data'

In [6]:
# Reading data and dropping usles or almost empty cols
df = pd.read_csv(DATA_PATH / 'data.csv', low_memory=False).drop(['Po', 'Pa', 'ff10', 'ff3', 'N', 'W1', 'W2', 'Tn', 'Tx', 'Cl', 'Nh', 'Cm', 'Ch', 'VV', 'RRR', 'tR', 'E', 'Tg', 'E\'', 'sss', 'Td'], axis=1)

In [7]:
# reverse the df to go from oldes to the newest
df = df.iloc[::-1]

<h2>Relevant Cols</h2>
- T is temperature in Celsius<br>
- P is atmospheric pressure<br>
- U is relative humidity (%) at a hight of 2 meters<br>
- DD is a mean wind direction<br>
- Ff is a mean wind speed<br>
- WW is a weather phenomena<br>
- H is the clouds hight<br>

In [8]:
df.head(10)

,date,T,P,U,DD,Ff,WW,H
64309,26/01/2013 00:00,2.1,745.9,95.0,Wind blowing from the south,6.0,Mist.,200-300
64308,26/01/2013 03:00,1.0,745.6,98.0,Wind blowing from the west-southwest,5.0,"Rain, freezing, moderate or heavy.",300-600
64307,26/01/2013 06:00,2.4,745.6,91.0,Wind blowing from the south-west,2.0,,1500-2000
64306,26/01/2013 09:00,3.0,746.7,72.0,Wind blowing from the west-northwest,6.0,,"2500 or more, or no clouds."
64305,26/01/2013 12:00,4.1,748.0,66.0,Wind blowing from the west,5.0,,"2500 or more, or no clouds."
64304,26/01/2013 15:00,4.4,747.7,65.0,Wind blowing from the west-southwest,1.0,,"2500 or more, or no clouds."
64303,26/01/2013 18:00,2.9,745.9,83.0,Wind blowing from the south-southwest,8.0,,"2500 or more, or no clouds."
64302,26/01/2013 21:00,3.5,741.8,97.0,Wind blowing from the south-southeast,7.0,"Rain, not freezing, continuous, slight at time...",200-300
64301,27/01/2013 00:00,4.1,736.7,99.0,Wind blowing from the south,12.0,Snow not falling as shower(s).,200-300
64300,27/01/2013 03:00,4.9,732.1,98.0,Wind blowing from the south,7.0,,200-300

In [9]:
df.tail(10)

,date,T,P,U,DD,Ff,WW,H
9,25/01/2021 13:00,3.1,753.6,91.0,Wind blowing from the north-west,5.0,"Drizzle and rain, slight.",300-600
8,25/01/2021 14:00,4.3,753.8,82.0,Wind blowing from the west-northwest,4.0,Rain (not freezing).,600-1000
7,25/01/2021 15:00,4.3,754.1,77.0,Wind blowing from the north-west,5.0,,1000-1500
6,25/01/2021 16:00,3.2,754.9,82.0,Wind blowing from the west-northwest,4.0,,"2500 or more, or no clouds."
5,25/01/2021 17:00,2.6,755.3,86.0,Wind blowing from the west,3.0,,1000-1500
4,25/01/2021 18:00,2.7,755.8,86.0,Wind blowing from the west-northwest,4.0,Rain (not freezing).,600-1000
3,25/01/2021 19:00,2.0,756.1,86.0,Wind blowing from the west-northwest,2.0,,600-1000
2,25/01/2021 20:00,1.9,756.5,86.0,Wind blowing from the west-northwest,3.0,,600-1000
1,25/01/2021 21:00,2.3,757.0,82.0,Wind blowing from the west,3.0,,600-1000
0,25/01/2021 22:00,2.3,757.3,81.0,Wind blowing from the west,4.0,,600-1000

In [10]:
# check the unique in DD col
df['DD'].value_counts()

Wind blowing from the south              10110
Wind blowing from the west                5072
Wind blowing from the south-southwest     4656
Wind blowing from the north-west          4652
Wind blowing from the north               4479
Wind blowing from the south-southeast     4396
Wind blowing from the west-northwest      4320
Wind blowing from the south-west          4302
Wind blowing from the north-northwest     4209
Wind blowing from the west-southwest      3374
Wind blowing from the south-east          3149
Wind blowing from the east-southeast      2557
Wind blowing from the east                2476
Wind blowing from the north-northeast     1755
Wind blowing from the north-east          1255
Wind blowing from the east-northeast      1192
Calm, no wind                              413
Name: DD, dtype: int64

In [11]:
# replace unique values and NaN values in a DD col
my_map = {
    None: 0,
    "Wind blowing from the south": 1,
    "Wind blowing from the west": 2,
    "Wind blowing from the south-southwest": 3,
    "Wind blowing from the north-west": 4,
    "Wind blowing from the north": 5,
    "Wind blowing from the south-southeast": 6,
    "Wind blowing from the west-northwest": 7,
    "Wind blowing from the south-west": 8,
    "Wind blowing from the north-northwest": 9,
    "Wind blowing from the west-southwest": 10,
    "Wind blowing from the south-east": 11,
    "Wind blowing from the east-southeast": 12,
    "Wind blowing from the east": 13,
    "Wind blowing from the north-northeast": 14,
    "Wind blowing from the north-east": 15,
    "Wind blowing from the east-northeast": 16,
    "Calm, no wind": 17,
}

df.replace(my_map, inplace=True)

df.head(10)

,date,T,P,U,DD,Ff,WW,H
64309,26/01/2013 00:00,2.1,745.9,95.0,1,6.0,Mist.,200-300
64308,26/01/2013 03:00,1.0,745.6,98.0,10,5.0,"Rain, freezing, moderate or heavy.",300-600
64307,26/01/2013 06:00,2.4,745.6,91.0,8,2.0,,1500-2000
64306,26/01/2013 09:00,3.0,746.7,72.0,7,6.0,,"2500 or more, or no clouds."
64305,26/01/2013 12:00,4.1,748.0,66.0,2,5.0,,"2500 or more, or no clouds."
64304,26/01/2013 15:00,4.4,747.7,65.0,10,1.0,,"2500 or more, or no clouds."
64303,26/01/2013 18:00,2.9,745.9,83.0,3,8.0,,"2500 or more, or no clouds."
64302,26/01/2013 21:00,3.5,741.8,97.0,6,7.0,"Rain, not freezing, continuous, slight at time...",200-300
64301,27/01/2013 00:00,4.1,736.7,99.0,1,12.0,Snow not falling as shower(s).,200-300
64300,27/01/2013 03:00,4.9,732.1,98.0,1,7.0,,200-300

In [12]:
# check the unique in H col
print(df['H'].value_counts())

2500 or more, or no clouds.    21366
1000-1500                      10644
300-600                         7931
1500-2000                       6763
600-1000                        6560
200-300                         4825
100-200                         2820
2000-2500                       1404
50-100                           925
Less than  50                    721
0                                351
Name: H, dtype: int64

In [13]:
# replace unique values and NaN values in a H col
my_map = {
    "2500 or more, or no clouds.": 10,
    "1000-1500": 9,
    "300-600": 8,
    "1500-2000": 7,
    "600-1000": 6,
    "200-300": 5,
    "100-200": 4,
    "2000-2500": 3,
    "50-100": 2,
    "Less than  50": 1,
    "0": 0,
}

df.replace(my_map, inplace=True)

df.head(10)

,date,T,P,U,DD,Ff,WW,H
64309,26/01/2013 00:00,2.1,745.9,95.0,1,6.0,Mist.,5
64308,26/01/2013 03:00,1.0,745.6,98.0,10,5.0,"Rain, freezing, moderate or heavy.",8
64307,26/01/2013 06:00,2.4,745.6,91.0,8,2.0,,7
64306,26/01/2013 09:00,3.0,746.7,72.0,7,6.0,,10
64305,26/01/2013 12:00,4.1,748.0,66.0,2,5.0,,10
64304,26/01/2013 15:00,4.4,747.7,65.0,10,1.0,,10
64303,26/01/2013 18:00,2.9,745.9,83.0,3,8.0,,10
64302,26/01/2013 21:00,3.5,741.8,97.0,6,7.0,"Rain, not freezing, continuous, slight at time...",5
64301,27/01/2013 00:00,4.1,736.7,99.0,1,12.0,Snow not falling as shower(s).,5
64300,27/01/2013 03:00,4.9,732.1,98.0,1,7.0,,5

In [14]:
print(df.isna().sum())

date    0
T       0
P       0
U       0
DD      0
Ff      0
WW      0
H       0
dtype: int64

Then we have to deal with col WW which represent some weather states. This is a bit more complicated because there is some analysis required. Bellow we can see all of the unique values. By examining them we can observe that there are some key words that repeat such as (rain, snow, fog, etc)

In [15]:
print(df['WW'].value_counts().index.to_list())

[' ', 'Rain (not freezing). ', 'Rain shower(s) or intermittent rain, slight. ', 'Haze or smoke, or dust in suspension in the air, visibility equal to, or greater than, 1 km. ', 'Rain, not freezing, moderate. ', 'Rain, not freezing, slight. ', 'Mist. ', 'Rain shower(s) or intermittent rain, moderate. ', 'Drizzle, not freezing, slight. ', 'Fog ', 'Drizzle and rain, slight. ', 'Fog or ice fog, has begun or become thicker during the past hour. ', 'Snow ', 'Drizzle (not freezing) or snow grains. ', 'Rain, not freezing, heavy. ', 'Drizzle, not freezing, moderate. ', 'Fog or ice fog, no appreciable change during the past hour. ', 'Precipitation ', 'Precipitation, slight or moderate. ', 'Rain and snow or ice pellets not falling as shower(s). ', 'Drizzle and rain, moderate or heavy. ', 'Fog or ice fog, has become thinner during the past hour. ', 'Snow shower(s) or intermittent snow, slight. ', 'Rain shower(s) or intermittent rain, heavy. ', 'Snow, slight. ', 'Rain (or drizzle) and snow, slight. ', 'Snow grains ', 'Snow, moderate. ', 'Snow shower(s) or intermittent snow, moderate. ', 'Rain shower(s), moderate or heavy. ', 'Visibility reduced by smoke, e.g. veldt or forest fires, industrial smoke or volcanic ashes. ', 'Drizzle, not freezing, heavy. ', 'Rain shower(s) or intermittent rain, violent. ', 'Freezing drizzle or freezing rain not falling as shower(s). ', 'Rain, not freezing, continuous, slight at time of observation. ', 'Fog or ice fog in patches. ', 'Snow shower(s), slight. ', 'Rain, not freezing, intermittent, moderate at time of observation. ', 'Rain shower(s), violent. ', 'Rain (not freezing) not falling as shower(s). ', 'Severe duststorm or sandstorm, no appreciable change during the preceding hour. ', 'Drizzle, not freezing, continuous, slight at time of observation. ', 'Freezing precipitation, slight or moderate. ', 'Ice pellets, slight. ', 'Freezing drizzle or freezing rain. ', 'Snow not falling as shower(s). ', 'Solid precipitation, slight or moderate. ', 'Ice pellets, moderate. ', 'Drizzle (not freezing) or snow grains not falling as shower(s). ', 'Liquid precipitation, heavy. ', 'Continuous fall of snowflakes, slight at time of observation. ', 'Rain, not freezing, continuous, moderate at time of observation. ', 'Drizzle, freezing, moderate or heavy (dense). ', 'Drizzle, not freezing, intermittent, moderate at time of observation. ', 'Snow shower(s), moderate or heavy. ', 'Rain, freezing, moderate or heavy. ', 'Fog, depositing rime. ', 'Severe duststorm or sandstorm has decreased during the preceding hour. ', 'Rain. ', 'Slight or moderate duststorm or sandstorm has begun or has increased during the preceding hour. ', 'Intermittent fall of snowflakes, moderate at time of observation. ', 'Shower(s) of rain and snow mixed, moderate or heavy. ', 'Liquid precipitation, slight or moderate. ', 'Freezing precipitation, heavy. ', 'Snow, heavy. ', 'Intermittent fall of snowflakes, heavy at time of observation. ', 'Hail ', 'Shower(s) of rain and snow mixed, slight. ']

In [16]:
# this was a testing code block that just shows all of the different subgroups I chose
# there is a problem that in some cases it can have both for example 'Shower(s) of rain and snow mixed, slight. '
# thus we need somehow deal with this problem
# the solution I have is devide col WW to 9 separete cols that will have bool value 1 or 0 for each of the states
rain = []
snow = []
fog = []
hail = []
drizzle = []
precipitation = []
ice_pellets = []
other = []

for st in df['WW'].value_counts().index.to_list():
    if 'rain' in st.lower():
        rain.append(st)
    elif 'snow' in st.lower():
        snow.append(st)
    elif 'fog' in st.lower():
        fog.append(st)
    elif 'hail' in st.lower():
        hail.append(st)
    elif 'drizzle' in st.lower():
        drizzle.append(st)
    elif 'precipitation' in st.lower():
        drizzle.append(st)
    elif 'ice pellets' in st.lower():
        ice_pellets.append(st)
    elif st != ' ':
        other.append(st)
    else:
        print(st)

In [17]:
def helper(row):
    """Matches re pattern in other words looks for some of the key words"""
    my_re = "(rain|snow|fog|hail|drizzle|precipitation|ice_pellets)"
    if not bool(re.search(my_re, row['WW'].lower())) and row['WW'] != ' ':
        return 1
    return 0 

# split the cols and drop the WW col
df['rain'] = df.apply(lambda row: 1 if 'rain' in row['WW'].lower() else 0, axis=1)
df['snow'] = df.apply(lambda row: 1 if 'snow' in row['WW'].lower() else 0, axis=1)
df['fog'] = df.apply(lambda row: 1 if 'fog' in row['WW'].lower() else 0, axis=1)
df['hail'] = df.apply(lambda row: 1 if 'hail' in row['WW'].lower() else 0, axis=1)
df['drizzle'] = df.apply(lambda row: 1 if 'drizzle' in row['WW'].lower() else 0, axis=1)
df['precipitation'] = df.apply(lambda row: 1 if 'precipitation' in row['WW'].lower() else 0, axis=1)
df['ice_pellets'] = df.apply(lambda row: 1 if 'ice pellets' in row['WW'].lower() else 0, axis=1)
df['other'] = df.apply(helper, axis=1)

df.drop(['WW'], axis=1, inplace=True)

In [18]:
# rename colnames to soething reasonable
names = {
    "T": "temperature",
    "P": "pressure",
    "U": "humidity",
    "DD": "wind_dir",
    "Ff": "wind_speed",
    "H": "coluds_hight",
}
df.rename(columns=names, inplace=True)

In [19]:
# colapse the df to days and order them by year -> mont -> day
df['date'] = pd.to_datetime(df['date'])
df.index = df['date']
df = df.loc[ df['date'].dt.year < 2021 ]
df.drop(['date'], axis=1, inplace=True)

In [20]:
df = df.groupby(by=[df.index.year, df.index.month, df.index.day]).mean()

df['rain'] = np.ceil(df['rain'])
df['snow'] = np.ceil(df['snow']) 
df['fog'] = np.ceil(df['fog']) 
df['hail'] = np.ceil(df['hail']) 
df['drizzle'] = np.ceil(df['drizzle']) 
df['precipitation'] = np.ceil(df['precipitation']) 
df['ice_pellets'] = np.ceil(df['ice_pellets']) 
df['rain'] = np.ceil(df['other'])
df['coluds_hight'] = np.round(df['coluds_hight'])
df['wind_dir'] = np.round(df['wind_dir'])


df = df.astype({"rain":'int', "snow":'int', "fog":'int', "hail":'int', "drizzle":'int', "precipitation":'int', "ice_pellets":'int'})

In [21]:
df.head(10)

                temperature    pressure   humidity  wind_dir  wind_speed  \
date date date
2013 1    2        3.175000  747.637500  87.375000       5.0    4.125000
          3        4.787500  774.800000  77.000000       8.0    3.000000
          4        1.950000  764.175000  63.125000      10.0    2.250000
          5        8.000000  764.787500  58.000000       6.0    6.375000
          6       10.637500  766.562500  75.375000       5.0    3.750000
          7       12.800000  757.025000  65.125000       6.0    2.875000
          8       15.425000  755.000000  93.625000       8.0    4.000000
          9       14.362500  763.375000  64.625000       5.0    4.000000
          10      12.237500  760.845833  74.416667       6.0    6.750000
          11       6.408333  748.887500  76.708333       7.0    5.416667

                coluds_hight  rain  snow  fog  hail  drizzle  precipitation  \
date date date
2013 1    2              8.0     0     1    0     0        1              0
          3              8.0     0     0    0     0        0              0
          4              9.0     0     0    0     0        0              0
          5              9.0     0     1    0     0        0              0
          6              8.0     0     1    0     0        0              0
          7              8.0     0     1    0     0        0              0
          8              5.0     0     1    0     0        0              0
          9              8.0     0     0    0     0        0              0
          10             7.0     0     0    0     0        0              0
          11            10.0     0     0    0     0        0              0

                ice_pellets  other
date date date
2013 1    2               1    0.0
          3               0    0.0
          4               0    0.0
          5               1    0.0
          6               1    0.0
          7               1    0.0
          8               1    0.0
          9               0    0.0
          10              0    0.0
          11              0    0.0

In [22]:
# we will forward fill the missing data scince it is most apropriate in this case
df.ffill(axis=0, inplace=True)

print(df.isna().sum())

temperature      0
pressure         0
humidity         0
wind_dir         0
wind_speed       0
coluds_hight     0
rain             0
snow             0
fog              0
hail             0
drizzle          0
precipitation    0
ice_pellets      0
other            0
dtype: int64

In [23]:
# save the result to new csv for later use
save_to = Path("__file__").absolute().parent / 'data' / 'data_cleaned.csv'

df.to_csv(save_to, date_format='%Y%m%d')